version: '3.3'
services:
  server:
    build: ./backend
    container_name: server
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017
      - JWT_SECRET=VerySecretSecret
      - GMAIL_ACCOUNT=findmytutor2020@gmail.com
      - process.env.GMAIL_PASSWORD=Zxcv12345
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    networks:
      - mongodb
    ports:
      - "3000:3000"
  client:
    build: ./frontend
    container_name: client
    environment:
      BASE_URL: backend:3000
    ports:
      - 8080:80
    networks:
      - mongodb
    depends_on:
      - server

  mongodb:
    image: mongo:latest
    container_name: mongodb
#    environment:
#      - MONGO_DATA_DIR=/data/db
#    volumes:
#      - ./data/:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongodb
networks:
  mongodb:
    driver: bridge
